force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Approval</fullName>
                <default>true</default>
                <label>Waiting for Approval</label>
            </value>
            <value>
                <fullName>Fully Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Auto_Approve__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approve__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Approve</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Schedule_TimesheetRequest.cls
/**
 * @author [AcekBecek]
 * @email [nurazispakaya16@mail.com]
 * @create date 2024-03-24 15:42:28
 * @modify date 2024-03-24 15:42:28
 * @desc [Schedule Controller for Timesheet batch]
 */
global class Schedule_TimesheetRequest implements Schedulable {
    
    public void execute(SchedulableContext sc){

        if(Date.today().day() == 25){
            updateApprovalStatus(25);
        }
        

        Batch_TimesheetRequest batch = new Batch_TimesheetRequest();
        ID batchprocessid = Database.executeBatch(batch, 200);

    }

    public static List<Database.SaveResult> updateApprovalStatus(Integer days){

        List<Timesheet__c> listTimesheet = [
            SELECT 
                Id, Approval_Status__c, Auto_Approve__c
            FROM Timesheet__c
            WHERE 
                Day_of_Creation__c =: days AND Approval_Status__c = 'Waiting for Approval'
        ];

        if(listTimesheet.size() == 0 ){
            return null;
        }

        for(Timesheet__c ts : listTimesheet){
            ts.Approval_Status__c = 'Fully Approved';
            ts.Auto_Approve__c = true;
        }

        Database.SaveResult[] listResult = Database.update(listTimesheet, false);

        return listResult;
    }

}