force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Approval</fullName>
                <default>true</default>
                <label>Waiting for Approval</label>
            </value>
            <value>
                <fullName>Fully Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet_Approval__c/Timesheet_Approval__c.object-meta.xml
<CustomObject>
    <label>Timesheet Approval</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_Approval__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Timesheet Approvals</relationshipLabel>
    <relationshipName>Timesheet_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/lwc_ApprovalTimesheetController.cls
global with sharing class lwc_ApprovalTimesheetController {
   
    @AuraEnabled
    public static string ApproverName(Id recordPageId){
        try {
            List<Timesheet_Approval__c>  timesheetApprovals = [
                SELECT Id, Approver__r.Name 
                FROM Timesheet_Approval__c 
                WHERE Id = : recordPageId limit 1
                ];
            
            return timesheetApprovals[0].Approver__r.Name;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class timesheetWrapper{
        public string recordid;
        public string ApprovalStatus;
    }

    @AuraEnabled
    public static string updateApprovalStatus(String Timesheets){
        try {

            List<Timesheet__c> obj_timesheets = new List<Timesheet__c>();
            List<timesheetWrapper> listTimesheet = (List<timesheetWrapper>)JSON.deserialize(Timesheets,List<timesheetWrapper>.class);

            for (timesheetWrapper singleTimesheet : listTimesheet) {
                obj_timesheets.add(new Timesheet__c(
                    Id = singleTimesheet.recordid, 
                    Approval_Status__c = singleTimesheet.ApprovalStatus
                    ));
            }

            Database.update(obj_timesheets);

            return ''+obj_timesheets;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    

}